spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF8&useUnicode=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

zuul:
  routes:
    common:
      path: /common/**
      serviceId: user-common-server